# Generated by Django 4.2.29 on 2026-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Collectible',
        ),
        migrations.RenameModel(
            old_name='UserInventory',
            new_name='UserCollection',
        ),
        migrations.RenameModel(
            old_name='PriceHistory',
            new_name='Market_Price',
        ),
        migrations.AddField(
            model_name='collectible',
            name='imgurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercollection',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
